module.exports = [
	{text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"},
	{text: "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done.", author: "Vince Lombardi"},
	{text: "Don't let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki"},
	{text: "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.", author: "Jane Smiley"},
	{text: "You can do anything, but not everything.", author: "Anonymous"},
	{text: "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", author: "Theodore N. Vail"},
	{text: "Fortune sides with him who dares.", author: "Virgil"},
	{text: "The ones who are crazy enough to think they can change the world, are the ones that do.", author: "Anonymous"},
	{text: "People rarely succeed unless they have fun in what they are doing.", author: "Dale Carnegie"},
	{text: "Don't be afraid to give up the good to go for the great", author:  "John D. Rockefeller"},
	{text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Lorimer"},
	{text: "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed", author:  "Ray Goforth"},
	{text: "You may only succeed if you desire succeeding; you may only fail if you do not mind failing.", author: "Philippos"},
	{text: "You must expect great things of yourself before you can do them", author:  "Michael Jordan"},
	{text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt"},
	{text: "Successful people do what unsuccessful people are not willing to doDon't wish it were easier, wish you were better.", author: "Jim Rohn"},
	{text: "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.", author: "Anonymous "},
	{text: "If you are not willing to risk the usual you will have to settle for the ordinary.", author: "Jim Rohn"},
	{text: "Take up one idea. Make that one idea your life -- think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.", author: "Swami Vivekananda"},
	{text: "The number one reason people fail in life is because they listen to their friends, family, and neighbors", author:  "Napoleon Hill"},
	{text: "Nothing in the world is more common than unsuccessful people with talent.", author: "Anonymous"},
	{text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader"},
	{text: "To accomplish great things, we must not only act, but also dream, not only plan, but also believe", author: " Anatole France"},
	{text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous"},
	{text: "Blessed are those who can give without remembering and take without forgetting.", author: "Anonymous"},
	{text: "Don't raise your voice, improve your argument.", author: "Anonymous"},
	{text: "Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others", author:  " John C. Maxwell"},
	{text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou"},
	{text: "What seems to us as bitter trials are often blessings in disguise", author: " Oscar Wilde"},
	{text: "Opportunities don't happen, you create them.", author: "Chris Grosser"},
	{text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Anonymous"},
	{text: "Life is not about finding yourself. Life is about creating yourself.", author: "Lolly Daskal"},
	{text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison"},
	{text: "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.", author: "Swami Vivekananda"},
	{text: "Things work out best for those who make the best of how things work out.", author: "John Wooden"},
	{text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt"},
	{text: "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work", author:  "Thomas J. Watson"},
	{text: "Successful entrepreneurs are givers and not takers of positive energy.", author: "Anonymous"},
	{text: "If you can't explain it simply, you don't understand it well enough. ", author: "Albert Einstein"},
	{text: "To live a creative life, we must lose our fear of being wrong.", author: "Anonymous"},
	{text: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville"},
	{text: "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter", author:  "Francis Chan"},
	{text: "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.", author: "Booker T. Washington"},
	{text: "No masterpiece was ever created by a lazy artist", author: " Anonymous"},
	{text: "A real entrepreneur is somebody who has no safety net underneath them.", author: "Henry Kravis"},
	{text: "Courage is resistance to fear, mastery of fear - not absense of fear", author:  "Mark Twain"},
	{text: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney"},
	{text: "When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.", author: "Audre Lorde"},
	{text: "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.", author: "Dr. APJ Kalam "},
	{text: "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", author: "Wayne Dyer"},
	{text: "When you stop chasing the wrong things you give the right things a chance to catch you.", author: "Lolly Daskal"},
	{text: "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well", author:  "Diane Ackerman"},
	{text: "To be successful you must accept all challenges that come your way. You can't just accept the ones you like", author:  "Mike Gafka"},
	{text: "If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it.", author: "Kim Garst"},
	{text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain"},
	{text: "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.", author: "Nathaniel Hawthorne"},
	{text: "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing", author:  "Martha Stewart "},
	{text: "Only put off until tomorrow what you are willing to die having left undone.", author: "Pablo Picasso"},
	{text: "Try not to become a person of success, but rather try to become a person of value. ", author: "Albert Einstein"},
	{text: "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.", author: "Mark Caine"},
	{text: "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul.", author: "Ella Wheeler Wilcox"},
	{text: "The only place where success comes before work is in the dictionary", author:  "Vidal Sassoon"},
	{text: "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.", author: " Jim Rohn"},
	{text: "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life", author:  "Steve Jobs"},
	{text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis"},
	{text: "Do one thing every day that scares you.", author: "Anonymous"},
	{text: "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily", author:  "Zig Ziglar"},
	{text: "Trust because you are willing to accept the risk, not because it's safe or certain.", author: "Anonymous"},
	{text: "It's not what you look at that matters, it's what you see.", author: "Anonymous"},
	{text: "If you genuinely want something, don't wait for it -- teach yourself to be impatient.", author: "Gurbaksh Chahal"},
	{text: "If you do what you always did, you will get what you always got.", author: "Anonymous"},
	{text: "Success is the sum of small efforts, repeated day-in and day-out", author:  "Robert Collier"},
	{text: "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.", author: "Tony Robbins"},
	{text: "Little minds are tamed and subdued by misfortune; but great minds rise above it.", author: "Washington Irving"},
	{text: "Don't let what you cannot do interfere with what you can do.", author: "John R. Wooden"},
	{text: "Success does not consist in never making mistakes but in never making the same one a second time.", author: "George Bernard Shaw"},
	{text: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford"},
	{text: "As we look ahead into the next century, leaders will be those who empower others.", author: "Bill Gates"},
	{text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun"},
	{text: "What's the point of being alive if you don't at least try to do something remarkable.", author: "Anonymous"},
	{text: "You may have to fight a battle more than once to win it", author:  "Margaret Thatcher"},
	{text: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", author: "David Brinkley"},
	{text: "If you're going through hell keep going", author:  "Winston Churchill"},
	{text: "If you want to achieve greatness stop asking for permission.", author: "Anonymous"},
	{text: "Just when the caterpillar thought the world was ending, he turned into a butterfly.", author: "Proverb"},
	{text: "The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them.", author: "Denis Watiley"},
	{text: "The distance between insanity and genius is measured only by success.", author: "Bruce Feirstein"},
	{text: "The starting point of all achievement is desire.", author: "Napolean Hill"},
	{text: "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.", author: "Dale Carnegie"},
	{text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote"},
	{text: "Your problem isn't the problem. Your reaction is the problem.", author: "Anonymous"},
	{text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak"},
	{text: "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!", author: "T. Harv Eker"},
	{text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie"},
	{text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee"},
	{text: "The best reason to start an organization is to make meaning; to create a product or service to make the world a better place.", author: "Guy Kawasaki"},
	{text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs"},
	{text: "I find that the harder I work, the more luck I seem to have", author:  "Thomas Jefferson"},
	{text: "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.", author: "Vaibhav Shah"},
	{text: "We become what we think about most of the time, and that's the strangest secret.", author: "Earl Nightingale"}
];
